language: node_js

node_js:
  - "7"

branches:
  only:
    - master 
before_install:
  - npm install -g hexo-cli

install:
  - npm install

script:
  - git submodule init
  - git submodule update
  - hexo generate
  - sed -i'' "/^ *repo/s~git@github\.com:~https://${GH_TOKEN}@github.com/~" _config.yml
  - hexo deploy --silent

